import { createTitle } from "../components/JobSelectionComponent/jobGenerator";

const initialState = {
  // s1
  s1: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false,
    c10: false,
    c11: false,
    c12: false,
    c13: false,
    c14: false,
    c16b: false,
    c16c: false,
    c15: false,
    c16: false,
    c17: false,
    c18: false,
    c19: false,
    c20: false,
    c21: false,
    c22: false,
    c23: false,
    c24: false,
    c25: false,
    c26: false,
    c27: false,
    c28: false,
    c29: false,
    c30: false,
    c31: false,
    c32: false
  },

  startBurning: false,
  playerNameInput: "",
  playerNameSaved: "",
  playerOccupationSaved: "",
  playerOccupationRadio: "",
  petOwnerInput: "",
  petTypeInput: "",
  petNameInput: "",
  petOwnerInputSaved: "",
  petTypeInputSaved: "",
  petNameInputSaved: "",
  newBadgeReceived: false,

  // s2
  s2: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false,
    c10: false,
    c11: false,
    c12: false,
    c13: false,
    c14: false,
    c15: false,
    c16: false,
    c17: false,
    c18: false,
    c19: false,
    c20: false,
    c21: false,
    c22: false,
    c23: false,
    c24: false,
    c25: false,
    c26: false,
    c27: false,
    c28: false,
    c29: false,
    c30: false,
    c31: false,
    c32: false
  },

  // s3
  s3: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false
  },

  // s4
  s4: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false,
    c10: false,
    c11: false,
    c12: false,
    c13: false,
    c14: false,
    c15: false,
    c16: false,
    c17: false,
    c18: false,
    c19: false,
    c20: false,
    c21: false,
    c22: false,
    c23: false,
    c24: false,
    c25: false,
    c26: false,
    c27: false
  },
  reactedAngry: false,
  reactedNod: false,

  // s5
  s5: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false,
    c10: false,
    c11: false,
    c12: false,
    c13: false,
    c14: false
  },
  darkness: true,

  // s6
  s6: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false,
    c10: false,
    c11: false,
    c12: false,
    c13: false,
    c14: false,
    c15: false,
    c16: false,
    c17: false,
    c18: false,
    c19: false,
    c20: false,
    c21: false,
    c22: false,
    c23: false,
    c24: false,
    c25: false,
    c26: false,
    c27: false,
    c28: false,
    c29: false,
    c30: false,
    c31: false,
    c32: false,
    c33: false,
    c34: false,
    c35: false,
    c36: false,
    c37: false,
    c38: false,
    c39: false,
    c40: false,
    c41: false,
    c42: false
  },
  bToldHer: true,
  bFine: true,
  taskTaken: false,
  roleFulfilled: false,

  s7: {
    c0: true,
    c1: false,
    c2: false,
    c3: false,
    c4: false,
    c5: false,
    c6: false,
    c7: false,
    c8: false,
    c9: false
  },

  // global
  nieceName: "Olive",
  inLawName: "Dena",
  coworkerName: "Paolo",
  leadPet: "Igglefort",
  petTwo: "Najj",
  petThree: "Barringzen",
  petFour: "Tomte",

  // global jobItems
  jobItems: [
    { id: 1, title: createTitle() },
    { id: 2, title: createTitle() },
    { id: 3, title: createTitle() }
  ]
};

export default initialState;
