// TODO go through and make sure these are relevant, funny, non-problematic
export const jobFirst = [
  "Adaptive",
  "Administrative",
  "Assistant",
  "Associate",
  "Authorized",
  "Autonomous",
  "B2B",
  "B2C",
  "Best Practice",
  "Chief",
  "Civilian",
  "Collaborative",
  "Collective",
  "Common",
  "Company",
  "Consumer",
  "Corporate",
  "Creative",
  "Customer",
  "Data Loss",
  "Distributed",
  "Domestic",
  "Dynamic",
  "Educational",
  "Enterprise",
  "Essential",
  "Exclusive",
  "Executive",
  "Federal",
  "First",
  "First Level",
  "Foreign",
  "Future",
  "General",
  "Global",
  "Government",
  "Granular",
  "Head",
  "Holistic",
  "Independent",
  "Innovative",
  "Integrated",
  "Interactive",
  "Interim",
  "International",
  "Intuitive",
  "Lead",
  "Legal",
  "Local",
  "Major",
  "Millennial",
  "Minor",
  "Moral",
  "Native",
  "Offshore",
  "Opensource",
  "Original",
  "Organic",
  "Partial",
  "Planetary",
  "Premium",
  "Principal",
  "Proactive",
  "Professional",
  "Public",
  "Qualified",
  "Realtime",
  "Regional",
  "Responsible",
  "Retail",
  "Robust",
  "Scalable",
  "Seamless",
  "Second Level",
  "Secondary",
  "Semi-Public",
  "Senior",
  "Senior Associate",
  "Senior Strategic",
  "Social",
  "Static",
  "Strategic",
  "Structural",
  "Superior",
  "Target",
  "Third Level",
  "Universal",
  "Ubiquitous",
  "Vice",
  "Vintage",
  "Viral",
  "Virtual",
  "Worldwide"
];

export const jobSecond = [
  "Account",
  "Advertising",
  "Advice",
  "Agile",
  "Applications",
  "Art",
  "Assembly",
  "Asset",
  "Assurance",
  "Audit",
  "Balance",
  "Benchmark",
  "Brand",
  "Brand Research",
  "Budget",
  "Business",
  "Business Insights",
  "Business Analysis",
  "Career",
  "Case",
  "Change",
  "Change Managemant",
  "Channel",
  "Cloud",
  "Collaboration",
  "Commitment",
  "Committee",
  "Communications",
  "Community",
  "Competition",
  "Component",
  "Conception",
  "Confidence",
  "Construction",
  "Consumer",
  "Consumer Electronics",
  "Content",
  "Content Analysis",
  "Contract",
  "Convergence",
  "Corporate Development",
  "Corporate Identity",
  "Cost",
  "Creative",
  "Credit",
  "Credit Analysis",
  "Crisis",
  "Cross-Media",
  "Cross-Platform",
  "Cultivation",
  "Customer",
  "Deliverable",
  "Delivery",
  "Demographic",
  "Deployment",
  "Design",
  "Design Research",
  "Design Thinking",
  "Development",
  "DevOps",
  "Distribution",
  "E-Business",
  "E-Commerce",
  "Education",
  "E-Markets",
  "Electronics",
  "Embracement",
  "Emerging Markets",
  "Employment",
  "Enhancement",
  "Enduser",
  "Endurability",
  "Engagement",
  "Engineering",
  "Equity",
  "E-Services",
  "Ethics",
  "Event",
  "Evolution",
  "Evolvement",
  "Experimental",
  "Export",
  "Facility",
  "Finance",
  "Governance",
  "Guidance",
  "Grief",
  "Group",
  "Growth",
  "Hardware",
  "Health Care",
  "Helpdesk",
  "Heritage",
  "Human Resources",
  "IT",
  "Implementation",
  "Import",
  "Incentive",
  "Industry",
  "Infrastructure",
  "Innovation",
  "Insights",
  "Insurance",
  "Integration",
  "Interaction",
  "Interactive Advertising",
  "Interface",
  "Investment",
  "Iteration",
  "Knowledge",
  "Law",
  "Leverage",
  "Loan",
  "Logic",
  "Logistics",
  "Loyalty",
  "Management",
  "Market",
  "Market Research",
  "Marketing",
  "Marketing Solutions",
  "Matrix",
  "M-Commerce",
  "Media",
  "Media Research",
  "Merchandise",
  "Methodologies",
  "Metrics",
  "Model",
  "Monetization",
  "Monitoring",
  "Multimedia",
  "Multi Platform",
  "Native Solutions",
  "Native Advertising",
  "Network",
  "Niches",
  "Offshoring",
  "Operations",
  "Opportunity",
  "Optimisation",
  "Orchestration",
  "Order",
  "Outsourcing",
  "Paradigms",
  "Partnerships",
  "Payroll",
  "Performance",
  "Planning",
  "Policy",
  "Portal",
  "Positioning",
  "Privacy",
  "Process",
  "Product",
  "Product Advertising",
  "Product Lifecycle",
  "Product Marketing",
  "Product Placement",
  "Product Research",
  "Production",
  "Profit",
  "Project",
  "Project Management",
  "Promotion",
  "Propaganda",
  "Property",
  "Publicity",
  "Quality",
  "Real Estate",
  "Reassurance",
  "Relations",
  "Reproduction",
  "Research",
  "Resource",
  "Responsibility",
  "Risk",
  "ROI",
  "Sales",
  "Sanitation",
  "Security",
  "Service",
  "Six-Sigma",
  "Social",
  "Social Media",
  "Social Responsibility",
  "Software",
  "Solution",
  "Strategy",
  "Supply Chain",
  "Support",
  "Sustainability",
  "Syndicate",
  "Talent",
  "Target",
  "Taxation",
  "Technology",
  "Therapy",
  "Trade",
  "Trademark",
  "Trading",
  "Training",
  "Transaction",
  "Transparancy",
  "Transportation",
  "Travel",
  "User",
  "User Experience",
  "UX and HCI",
  "Value",
  "Visionary",
  "Wireless",
  "Web",
  "Workshop"
];

export const jobPosition = [
  "Accountant",
  "Administrator",
  "Advisor",
  "Advocate",
  "Agent",
  "Ambassador",
  "Analyst",
  "Architect",
  "Artist",
  "Associate",
  "Attourney",
  "Authority",
  "Broker",
  "Chairperson",
  "Coach",
  "Collaborateur",
  "Consultant",
  "Controller",
  "Coordinator",
  "Counsellor",
  "Deputy",
  "Deputy Officer",
  "Developer",
  "DevOp",
  "Digitalizer",
  "Director",
  "Dispatcher",
  "Editor",
  "Enabler",
  "Enforcer",
  "Engineer",
  "Enthusiast",
  "Evangelist",
  "Expert",
  "General",
  "Guru",
  "Hacker",
  "Hipster",
  "Inspector",
  "Instructor",
  "Intern",
  "Knowledgarian",
  "Lawyer",
  "Lobbyist",
  "Manager",
  "Manufacturer",
  "Marshall",
  "Mentor",
  "Modeler",
  "Officer",
  "Opener",
  "Operator",
  "Orchestrator",
  "Partner",
  "Practitioner",
  "President",
  "Principal",
  "Principal Deputy Officer",
  "Provider",
  "Regent",
  "Secretary",
  "Specialist",
  "Strategist",
  "Suggestor",
  "Supervisor",
  "Talent",
  "Technician",
  "Trader",
  "Trainer",
  "Tutor",
  "Vice",
  "Visionary",
  "Human"
];

export const companyName = [
  "Louza",
  "Wherethought",
  "Magnithim",
  "Slidforce",
  "Act"
];

export const companyType = [
  "Corp",
  "Consulting",
  "Studio",
  "Agency",
  "Bank",
  "Trading",
  "Vending",
  "Capital",
  ".com"
];

// TODO refactor
export const createTitle = () => {
  let f = "";
  f = f.concat(
    jobFirst[Math.floor(Math.random() * jobFirst.length)] +
      " " +
      jobSecond[Math.floor(Math.random() * jobSecond.length)] +
      " " +
      jobPosition[Math.floor(Math.random() * jobPosition.length)]
  );
  return f;
};

// TODO refactor
export const createCompany = () => {
  let x = "";
  x = x.concat(
    companyName[Math.floor(Math.random() * companyName.length)] +
      " " +
      companyType[Math.floor(Math.random() * companyType.length)]
  );
  return x;
};
